global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: [ 'localhost:9090']

  - job_name: nodee
    metrics_path: /metrics
    static_configs:
      - targets:  ['gwagsojeong-ui-macbookpro.local:9101']

  # A scrape configuration containing the Neo4j endpoint to scrape:
    # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'neo4j-prometheus'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
    # target: ip address of the Neo4j server
      - targets: [ 'localhost:2004']
